package org.cgiar.clarisa.model;
// Generated Apr 18, 2018 1:21:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * RepIndOrganizationType generated by hbm2java
 */
@Entity
@Table(name = "rep_ind_organization_types")
@NamedQuery(name = "RepIndOrganizationType.findAll", query = "SELECT riot FROM RepIndOrganizationType riot")
public class RepIndOrganizationType extends ClarisaBaseEntity implements java.io.Serializable {

  private static final long serialVersionUID = -2844095300386508539L;
  @Expose
  private String name;
  @Expose
  private String definition;

  public RepIndOrganizationType() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    RepIndOrganizationType other = (RepIndOrganizationType) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  @Column
  public String getDefinition() {
    return this.definition;
  }

  @Column
  public String getName() {
    return this.name;
  }


  public void setDefinition(String definition) {
    this.definition = definition;
  }

  public void setName(String name) {
    this.name = name;
  }
}